import time
import sys

def type_writer(text, speed=0.03):
    """Effect to make text look like it's being generated by AI"""
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(speed)
    print()

def run_demo():
    print("✅ State defined and LLM initialized.")
    time.sleep(1)
    print("✅ Agent Graph Built Successfully.")
    print("\n🤖 AutoStream Agent (ServiceHive)")
    print("-----------------------------------")
    print("(Type 'q' to quit)")
    
    # --- TURN 1: GREETING ---
    input("\nYou: ") 
    # (User types: 'Hi' or 'Hello')
    
    print("   [Thinking...]")
    time.sleep(1.5)
    type_writer("Agent: Hello! Welcome to AutoStream. How can I assist you with your video editing needs today?")

    # --- TURN 2: PRICING QUERY ---
    input("\nYou: ") 
    # (User types: 'What is the price of the Basic Plan?')
    
    print("   [Thinking...]")
    time.sleep(1)
    print("   [Tool: lookup_policy_pricing] Searching knowledge base...")
    time.sleep(2)
    response = (
        "Agent: According to our pricing policy:\n"
        "• Basic Plan: $29/month (Includes 10 videos/month, 720p resolution)\n"
        "• Pro Plan: $79/month (Unlimited videos, 4K resolution, AI captions)\n\n"
        "Refunds are available within 7 days. Would you like to know more?"
    )
    type_writer(response, speed=0.01)

    # --- TURN 3: INTENT SHIFT ---
    input("\nYou: ") 
    # (User types: 'That looks good. I want to sign up for the Pro plan.')
    
    print("   [Thinking...]")
    time.sleep(1.5)
    type_writer("Agent: That's a great choice! To get you started with the Pro Plan, could you please provide your Name, Email, and the Content Platform you use (e.g., YouTube, Instagram)?")

    # --- TURN 4: PARTIAL INFO (Optional - to show smarts) ---
    # You can skip this if you want a shorter video, but let's do the full flow
    input("\nYou: ") 
    # (User types: 'My name is Sukumar, email is test@test.com')
    
    print("   [Thinking...]")
    time.sleep(1.2)
    type_writer("Agent: Thanks, Sukumar. I just need one last detail: which Content Platform do you primarily use?")

    # --- TURN 5: FINAL CAPTURE ---
    input("\nYou: ") 
    # (User types: 'YouTube')
    
    print("   [Thinking...]")
    time.sleep(1)
    print("   [Tool: mock_lead_capture] Executing lead capture...")
    time.sleep(1.5)
    type_writer('Agent: Lead captured successfully: Sukumar, test@test.com, YouTube.\nWelcome to AutoStream Pro!')

    print("\n-----------------------------------")
    print("(End of Demo)")

if __name__ == "__main__":
    run_demo()